version: '3'
services:
  first_app:
    container_name: simple-app
    build:
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/tg_db
      SPRING_DATASOURCE_USERNAME: tg_user
      SPRING_DATASOURCE_PASSWORD: tg_pwd


    links:
      - postgres
      - redis-server
  postgres:
    container_name: chat-app_system
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tg_db
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: tg_pwd

  redis-server:
    hostname: redis
    container_name: chat-app_system-redis_db
    image: 'redis'
    ports:
      - "6379:6379"